import type { Feedback } from "@/lib/types/feedback";
import {
  FeedbackPriority,
  FeedbackSource,
  FeedbackStatus,
  FeedbackType,
} from "@/lib/types/feedback";

export const mockFeedback: Feedback[] = [
  {
    id: "1",
    createdAt: new Date("2024-01-15T10:30:00Z"),
    updatedAt: new Date("2024-01-15T10:30:00Z"),
    type: FeedbackType.CONTACT,
    source: FeedbackSource.CONTACT_PAGE,
    userId: "user_123",
    subject: "Question about memorial services",
    message: "I would like to know more about your memorial services and pricing options. Can someone contact me?",
    status: FeedbackStatus.NEW,
    priority: FeedbackPriority.MEDIUM,
    metadata: {
      email: "user@example.com",
      url: "/contact",
    },
    internalNotes: null,
  },
  {
    id: "2",
    createdAt: new Date("2024-01-14T14:20:00Z"),
    updatedAt: new Date("2024-01-14T15:45:00Z"),
    type: FeedbackType.FEATURE_REQUEST,
    source: FeedbackSource.FEATURE_REQUEST_CARD,
    userId: "user_456",
    subject: "Add dark mode support",
    message: "It would be great to have a dark mode option for the memorial pages. Many users prefer darker themes, especially for memorial content.",
    status: FeedbackStatus.IN_REVIEW,
    priority: FeedbackPriority.HIGH,
    metadata: {
      url: "/dashboard",
      userAgent: "Mozilla/5.0",
    },
    internalNotes: "This is a popular request. Consider adding to Q2 roadmap.",
  },
  {
    id: "3",
    createdAt: new Date("2024-01-13T09:15:00Z"),
    updatedAt: new Date("2024-01-13T09:15:00Z"),
    type: FeedbackType.BUG,
    source: FeedbackSource.INLINE_SURVEY,
    userId: "user_789",
    subject: "Image upload fails on mobile",
    message: "When trying to upload images on my iPhone, the upload button doesn't work. The page seems to freeze. This happens consistently on Safari iOS 17.",
    status: FeedbackStatus.NEW,
    priority: FeedbackPriority.HIGH,
    metadata: {
      url: "/entry/abc123/images/create",
      device: "mobile",
      browser: "Safari",
      os: "iOS 17",
    },
    internalNotes: null,
  },
  {
    id: "4",
    createdAt: new Date("2024-01-12T16:45:00Z"),
    updatedAt: new Date("2024-01-12T16:45:00Z"),
    type: FeedbackType.FEATURE_REQUEST,
    source: FeedbackSource.FEATURE_REQUEST_CARD,
    userId: "user_321",
    subject: "Export memorial as PDF",
    message: "I'd love to be able to export a memorial page as a PDF so I can share it offline or print it. This would be very useful for families.",
    status: FeedbackStatus.NEW,
    priority: FeedbackPriority.MEDIUM,
    metadata: {
      url: "/entry/def456",
    },
    internalNotes: null,
  },
  {
    id: "5",
    createdAt: new Date("2024-01-11T11:30:00Z"),
    updatedAt: new Date("2024-01-11T13:20:00Z"),
    type: FeedbackType.CONTACT,
    source: FeedbackSource.CONTACT_PAGE,
    userId: null,
    subject: "Account deletion request",
    message: "I need to delete my account and all associated data. Please help me with this process.",
    status: FeedbackStatus.RESOLVED,
    priority: FeedbackPriority.MEDIUM,
    metadata: {
      email: "user2@example.com",
      url: "/contact",
    },
    internalNotes: "Account deleted on 2024-01-11. User confirmed via email.",
  },
  {
    id: "6",
    createdAt: new Date("2024-01-10T08:00:00Z"),
    updatedAt: new Date("2024-01-10T08:00:00Z"),
    type: FeedbackType.BUG,
    source: FeedbackSource.INLINE_SURVEY,
    userId: "user_654",
    entryId: "entry_xyz",
    subject: "Obituary text formatting issue",
    message: "When I generate an obituary, the line breaks don't appear correctly. The text runs together without proper paragraph spacing.",
    status: FeedbackStatus.NEW,
    priority: FeedbackPriority.LOW,
    metadata: {
      url: "/entry/xyz789/obituaries/create",
    },
    internalNotes: null,
  },
  {
    id: "7",
    createdAt: new Date("2024-01-09T15:20:00Z"),
    updatedAt: new Date("2024-01-09T17:10:00Z"),
    type: FeedbackType.FEATURE_REQUEST,
    source: FeedbackSource.FEATURE_REQUEST_CARD,
    userId: "user_987",
    subject: "Add video support",
    message: "Would it be possible to add video uploads to memorial pages? Many families have video memories they'd like to share.",
    status: FeedbackStatus.IN_REVIEW,
    priority: FeedbackPriority.MEDIUM,
    metadata: {
      url: "/dashboard",
    },
    internalNotes: "Interesting idea. Need to consider storage costs and bandwidth.",
  },
  {
    id: "8",
    createdAt: new Date("2024-01-08T12:00:00Z"),
    updatedAt: new Date("2024-01-08T12:00:00Z"),
    type: FeedbackType.OTHER,
    source: FeedbackSource.CONTACT_PAGE,
    userId: "user_111",
    subject: "Thank you for your service",
    message: "I just wanted to say thank you for creating such a beautiful platform for memorials. It helped our family during a difficult time.",
    status: FeedbackStatus.RESOLVED,
    priority: FeedbackPriority.LOW,
    metadata: {
      email: "user3@example.com",
      url: "/contact",
    },
    internalNotes: "Positive feedback. No action needed.",
  },
  {
    id: "9",
    createdAt: new Date("2024-01-07T10:15:00Z"),
    updatedAt: new Date("2024-01-07T10:15:00Z"),
    type: FeedbackType.BUG,
    source: FeedbackSource.INLINE_SURVEY,
    userId: "user_222",
    subject: "Search functionality not working",
    message: "The search bar in the dashboard doesn't return any results, even when I know entries exist with matching names.",
    status: FeedbackStatus.DISMISSED,
    priority: FeedbackPriority.MEDIUM,
    metadata: {
      url: "/dashboard",
    },
    internalNotes: "User was searching for entries in wrong organization. Explained how org switching works.",
  },
  {
    id: "10",
    createdAt: new Date("2024-01-06T14:30:00Z"),
    updatedAt: new Date("2024-01-06T14:30:00Z"),
    type: FeedbackType.FEATURE_REQUEST,
    source: FeedbackSource.FEATURE_REQUEST_CARD,
    userId: "user_333",
    subject: "Collaborative editing",
    message: "It would be helpful if multiple family members could edit a memorial entry together, similar to Google Docs collaboration.",
    status: FeedbackStatus.NEW,
    priority: FeedbackPriority.HIGH,
    metadata: {
      url: "/entry/ghi789",
    },
    internalNotes: null,
  },
];

