CREATE TABLE "v1_pre_need_survey_audit_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"survey_id" uuid NOT NULL,
	"actor_type" varchar NOT NULL,
	"actor_id" text,
	"actor_name" text,
	"action" varchar NOT NULL,
	"previous_status" varchar,
	"new_status" varchar,
	"metadata" text,
	"created_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "v1_pre_need_survey_response" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"survey_id" uuid NOT NULL,
	"full_name" text,
	"preferred_name" text,
	"needs_access_codes" boolean,
	"phone_device_hint" text,
	"password_manager_hint" text,
	"access_details_location" text,
	"emergency_contact_name" text,
	"emergency_contact_relationship" text,
	"emergency_contact_phone" text,
	"emergency_contact_notes" text,
	"has_attorney" boolean,
	"attorney_name" text,
	"attorney_phone" text,
	"has_financial_advisor" boolean,
	"financial_advisor_name" text,
	"financial_advisor_phone" text,
	"has_will" varchar,
	"will_location" text,
	"will_attorney_name" text,
	"has_poa_financial" boolean,
	"has_poa_healthcare" boolean,
	"has_living_will" boolean,
	"has_health_care_proxy" boolean,
	"legal_docs_designated_person" text,
	"legal_docs_designated_phone" text,
	"legal_docs_location" text,
	"has_end_of_life_funding" boolean,
	"funding_location" text,
	"is_preneed_plan" boolean,
	"has_life_insurance" boolean,
	"life_insurance_company" text,
	"life_insurance_policy_location" text,
	"life_insurance_beneficiary" text,
	"banks_credit_unions" text,
	"investment_accounts" text,
	"other_financial_accounts" text,
	"account_details_location" text,
	"owns_or_rents_property" boolean,
	"property_address" text,
	"property_status" varchar,
	"property_contacts" text,
	"property_docs_location" text,
	"has_storage_unit" boolean,
	"has_safe_deposit_box" boolean,
	"has_po_box" boolean,
	"has_vehicles" boolean,
	"other_assets_details" text,
	"other_assets_access_info" text,
	"uses_password_manager" boolean,
	"password_manager_name" text,
	"master_password_location" text,
	"has_email_accounts" boolean,
	"has_social_media" boolean,
	"has_banking_apps" boolean,
	"has_streaming_subscriptions" boolean,
	"has_work_accounts" boolean,
	"has_cloud_storage" boolean,
	"login_info_location" text,
	"accounts_to_delete" text,
	"accounts_to_memorialize" text,
	"has_utility_payments" boolean,
	"has_subscription_payments" boolean,
	"has_insurance_payments" boolean,
	"has_charitable_donations" boolean,
	"payment_method" text,
	"primary_doctor_name" text,
	"primary_doctor_phone" text,
	"critical_medications" text,
	"major_health_conditions" text,
	"preferred_hospital" text,
	"organ_donation_preference" varchar,
	"has_funeral_arrangements" boolean,
	"funeral_home_provider" text,
	"arrangement_paperwork_location" text,
	"service_type_preference" varchar,
	"final_arrangement_preference" varchar,
	"religious_spiritual_notes" text,
	"obituary_key_points" text,
	"preferred_charities" text,
	"has_specific_items_for_people" boolean,
	"specific_items_doc_location" text,
	"person_to_notify_1_name" text,
	"person_to_notify_1_relationship" text,
	"person_to_notify_1_contact" text,
	"person_to_notify_2_name" text,
	"person_to_notify_2_relationship" text,
	"person_to_notify_2_contact" text,
	"employer_name" text,
	"hr_benefits_contact" text,
	"spare_keys_location" text,
	"car_keys_location" text,
	"safe_security_code_hint" text,
	"additional_information" text,
	"backup_person_1" text,
	"backup_person_2" text,
	"backup_location" text,
	"is_complete" boolean DEFAULT false NOT NULL,
	"completed_at" timestamp,
	"last_edited_at" timestamp,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "v1_pre_need_survey" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"organization_id" text,
	"entry_id" text,
	"title" text DEFAULT 'Pre-Need Survey' NOT NULL,
	"subject_name" text NOT NULL,
	"client_name" text,
	"client_email" text,
	"client_relationship" text,
	"status" varchar DEFAULT 'draft' NOT NULL,
	"status_changed_at" timestamp,
	"status_changed_by" text,
	"is_locked" boolean DEFAULT false NOT NULL,
	"locked_at" timestamp,
	"locked_by" text,
	"completion_percentage" integer DEFAULT 0 NOT NULL,
	"current_step" integer DEFAULT 1 NOT NULL,
	"last_client_access_at" timestamp,
	"share_link_id" uuid,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
ALTER TABLE "v1_entry_details" ADD COLUMN "generated_obit_summary" text;--> statement-breakpoint
ALTER TABLE "v1_share_link" ADD COLUMN "survey_id" uuid;--> statement-breakpoint
ALTER TABLE "v1_pre_need_survey_audit_log" ADD CONSTRAINT "v1_pre_need_survey_audit_log_survey_id_v1_pre_need_survey_id_fk" FOREIGN KEY ("survey_id") REFERENCES "public"."v1_pre_need_survey"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v1_pre_need_survey_response" ADD CONSTRAINT "v1_pre_need_survey_response_survey_id_v1_pre_need_survey_id_fk" FOREIGN KEY ("survey_id") REFERENCES "public"."v1_pre_need_survey"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v1_pre_need_survey" ADD CONSTRAINT "v1_pre_need_survey_user_id_v1_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."v1_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v1_pre_need_survey" ADD CONSTRAINT "v1_pre_need_survey_entry_id_v1_entry_id_fk" FOREIGN KEY ("entry_id") REFERENCES "public"."v1_entry"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v1_pre_need_survey" ADD CONSTRAINT "v1_pre_need_survey_status_changed_by_v1_user_id_fk" FOREIGN KEY ("status_changed_by") REFERENCES "public"."v1_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "v1_pre_need_survey" ADD CONSTRAINT "v1_pre_need_survey_locked_by_v1_user_id_fk" FOREIGN KEY ("locked_by") REFERENCES "public"."v1_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "pre_need_survey_audit_log_survey_id_idx" ON "v1_pre_need_survey_audit_log" USING btree ("survey_id");--> statement-breakpoint
CREATE INDEX "pre_need_survey_audit_log_created_at_idx" ON "v1_pre_need_survey_audit_log" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "pre_need_survey_response_survey_id_idx" ON "v1_pre_need_survey_response" USING btree ("survey_id");--> statement-breakpoint
CREATE INDEX "pre_need_survey_user_id_idx" ON "v1_pre_need_survey" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "pre_need_survey_organization_id_idx" ON "v1_pre_need_survey" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "pre_need_survey_entry_id_idx" ON "v1_pre_need_survey" USING btree ("entry_id");--> statement-breakpoint
CREATE INDEX "pre_need_survey_status_idx" ON "v1_pre_need_survey" USING btree ("status");--> statement-breakpoint
CREATE INDEX "share_link_survey_idx" ON "v1_share_link" USING btree ("survey_id");